version: "3.7"

services:

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.demo
    tty: true
    command: ["./wait-for-it.sh", "--timeout=0", "ui_app_1:8080", "--", "nginx", "-g", "daemon off;"]
    depends_on:
      - app
    ports:
      - '8000:443'

  app:
    build:
      context: shinyproxy
      dockerfile: Dockerfile.demo
    depends_on:
      - dns
    environment:
      - CURL_CA_BUNDLE=/root/consult.crt
    extra_hosts:
      - danvers:172.21.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dns:
    build:
      context: dns
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - danvers:172.21.0.1
    networks:
      default:
        ipv4_address: 172.23.0.100

networks:
  default:
    name: ui_network
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
