proxy:
  # bind-address: 127.0.0.1
  title: CONSULT
  logo-url: https://avatars1.githubusercontent.com/u/36307411?s=400&u=04f40378ef32955ff363a8144c028ec7ffe6838c&v=4
  heartbeat-rate: 20000
  heartbeat-timeout: 60000
  port: 8080
  authentication: ldap
  ldap:
    url: ldaps://danvers/dc=consult,dc=kcl,dc=ac,dc=uk
    user-dn-pattern: cn={0}
    manager-dn: cn=admin,dc=consult,dc=kcl,dc=ac,dc=uk
    manager-password: root
  docker:
    internal-networking: true
  specs:
  - id: dashboard
    display-name: Dashboard
    container-cmd: ["R", "-e", "shiny::runApp('/root/dashboard/app')"]
    container-image: consult-kcl/dashboard
    container-env:
      MESSAGE_PASSER_URL: danvers # Add port if running on same machine.
      MESSAGE_PASSER_PROTOCOL: https://
      CURL_CA_BUNDLE: /root/consult.crt
      # Study Parameters
      # (Allow for defaults)
      # Start time Defaults to NOW
      STUDY_START_TIMESTAMP: "2017-09-03 17:07:47 BST" # Temporary start
      # End time Defaults to 17 days from NOW
      STUDY_END_TIMESTAMP: "2020-09-03 17:07:47 BST" # Temporary end
      # Default is 3
      STUDY_TRIAL_PERIOD_DAYS: "3"
      # Disable Chatbot
      STUDY_CHATBOT_ACTIVE: "0"
      # every 21 days
      STUDY_PHQ_DAYS_FREQ: "21"
      # Do not randomize Recommendations
      RANDOMIZE_RECOMMENDATIONS: "0"
      # Use API for data
      USE_SAMPLE_DATA: "0"
      # UI - omit risk and recommendations tabs
      ACTIVE_TABS: "summary,bp,hr,ecg,mood,feedback,recommendations"
      # No visiable debug panel
      DEBUG_PANEL: "0"
    container-network: ui_network
    container-dns: ["172.23.0.100"]

server:
  useForwardHeaders: true
  servlet:
    context-path: /ui

logging:
  file:
    shinyproxy.log
  level:
    org.springframework.security.ldap: DEBUG
